# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "08hgblspaisx33ij735yri8nwf5zy0y2dzwh960r0aiwcwg8vbs9";
    x86_64-linux = "0h7zdb48jcfnm1plixasnqvxbxg5kp35laqzci9p2gq1b3f49g6w";
    armv7l-linux = "0sadm3ky5677c19jn1bkkq02afc76lc7gi9gwf8ax7lsnfhin3b9";
    aarch64-linux = "0f77yjzyjc0fazhr8kzjf9iqzp82dilakqycdbmm1mzbk0yknxk6";
    x86_64-darwin = "0v46yi2d0xf2i38h5q9975x4jh8yfqqw920jc9nhb4iql2cpngwj";
    aarch64-darwin = "1wxj5prg1f9jagmhc8v3gkagd29dybz6lyv988p7w87a7mm0a659";
  };

  urlMap = {
    i686-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.3.0/voiceflow_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.3.0/voiceflow_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.3.0/voiceflow_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.3.0/voiceflow_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.3.0/voiceflow_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.3.0/voiceflow_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "voiceflow";
  version = "1.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./voiceflow $out/bin/voiceflow
    installManPage ./manpages/voiceflow.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "The CLI for your Voiceflow projects";
    homepage = "https://voiceflow.xavidop.me";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
