# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "031acyj7mldwbyl6313wbgxhhif5k0p87w363pq5zcnz7sswq2wb";
    x86_64-linux = "06n0m92nw4sxcqixp15ahrnryp0bqy5bvvplg4vam4jrgpawrl5w";
    armv7l-linux = "1a1p3adcjvd5mpc3s2bmf182b4l2b6phk2czhbryqzxv6n211rrw";
    aarch64-linux = "03l7nsfddfxbw2956lwg2f238sr05sasj4922mvpc620892q6sw7";
    x86_64-darwin = "0dqc5fsaqjg4imdyrm59wznaqy3hjm4yzzh78dkcwal6pygk505k";
    aarch64-darwin = "1w6waipdydypfcyrqq9n6x6az092y4xv0adaw3417pkhn6bbr55l";
  };

  urlMap = {
    i686-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.34.3/voiceflow_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.34.3/voiceflow_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.34.3/voiceflow_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.34.3/voiceflow_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.34.3/voiceflow_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/xavidop/voiceflow-cli/releases/download/v1.34.3/voiceflow_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "voiceflow";
  version = "1.34.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./voiceflow $out/bin/voiceflow
    installManPage ./manpages/voiceflow.1.gz
    installShellCompletion ./completions/*
  '';

  meta = {
    description = "The CLI for your Voiceflow projects";
    homepage = "https://voiceflow.xavidop.me";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
